//Geting all data from the table
GET http://localhost:5000/data
//Insert data to into table 
POST http://localhost:5000/postdata
Content-Type: application/json

{
    "id":4,
    "name":"naveen",
    "mark":70,
    "grade":"B"
}

//Delete data throug mark in a table
DELETE http://localhost:5000/delete/data/70
//Delete data through id  in a table
DELETE http://localhost:5000/deletedata/4
//Delete data through name in a table
DELETE http://localhost:5000/data/raghu
//Update the data,Id through update name and mark
